---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: enable-fn-debug
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              args:
                - --debug
          # serviceAccountName: xfn-network-discovery
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-extra-resources
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-extra-resources:v0.0.3
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: enable-fn-debug
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-shell
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-shell:v0.3.0
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: enable-fn-debug
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-github-app-get-token
  annotations:
    # This tells crossplane beta render to connect to the function locally.
    # render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: 172.18.0.3:5000/function-github-app-get-token:latest
  packagePullPolicy: Always
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: enable-fn-debug
