apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrs.example.crossplane.io
spec:
  group: example.crossplane.io
  names:
    kind: XR
    singular: xr
    plural: xrs
  claimNames:
    kind: R
    singular: r
    plural: rs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: {}
            status:
              properties:
                atFunction:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
